(function() {
  var box = document.createElement('div');
  box.style.position = 'fixed';
  box.style.top = '50%';
  box.style.left = '50%';
  box.style.transform = 'translate(-50%, -50%)';
  box.style.width = '300px';
  box.style.height = '400px';
  box.style.backgroundColor = 'black';
  box.style.borderRadius = '10px';
  box.style.zIndex = '9999';
  box.style.opacity = '0';
  var logo1 = document.createElement('img');
  logo1.src = 'https://fatgarfield777.xyz/images/favicon.png';
  logo1.style.position = 'absolute';
  logo1.style.top = '10px';
  logo1.style.left = '10px';
  logo1.style.width = '60px';
  logo1.style.height = '60px';
  var logo2 = document.createElement('img');
  logo2.src = 'https://fatgarfield777.xyz/images/LithiumNetwork.png';
  logo2.style.position = 'absolute';
  logo2.style.top = '10px';
  logo2.style.right = '10px';
  logo2.style.width = '60px';
  logo2.style.height = '60px';
  var title = document.createElement('h2');
  title.textContent = 'UBG17 LINKS';
  title.style.position = 'absolute';
  title.style.top = '10px';
  title.style.left = '50%';
  title.style.transform = 'translateX(-50%)';
  title.style.color = 'white';
  title.style.textAlign = 'center';
  title.style.width = '100%';
  title.style.fontSize = '18px';
  var keyList = document.createElement('ul');
  keyList.style.position = 'absolute';
  keyList.style.top = '80px';
  keyList.style.left = '10px';
  keyList.style.color = 'white';
  keyList.style.listStyle = 'none';
  keyList.style.lineHeight = '1';
  var key1 = document.createElement('li');
  key1.textContent = '%E2%9C%85 - Definitely Unblocked';
  var key2 = document.createElement('li');
  key2.textContent = '%E2%9A%A0%EF%B8%8F - Maybe Blocked';
  var key3 = document.createElement('li');
  key3.textContent = '%E2%9D%8C - Definitely Blocked';
  keyList.appendChild(key1);
  keyList.appendChild(key2);
  keyList.appendChild(key3);
  var linkList = document.createElement('ul');
  linkList.style.position = 'absolute';
  linkList.style.top = '160px';
  linkList.style.left = '10px';
  linkList.style.color = 'white';
  linkList.style.width = '280px';
  linkList.style.listStyle = 'none';
  linkList.style.lineHeight = '1';
  var link1 = document.createElement('li');
  link1.innerHTML = '<a href="https://fatgarfield777.xyz" target="_blank">%E2%9D%8C - fatgarfield777.xyz</a>';
  var link2 = document.createElement('li');
  link2.innerHTML = '<a href="https://ug17.github.io" target="_blank">%E2%9C%85 - ug17.github.io</a>';
  var link3 = document.createElement('li');
  link3.innerHTML = '<a href="https://ubg17.up.railway.app" target="_blank">%E2%9C%85 - ubg17.up.railway.app</a>';
  var link4 = document.createElement('li');
  link4.innerHTML = '<a href="https://ug17.up.railway.app" target="_blank">%E2%9C%85 - ug17.up.railway.app</a>';
  var link5 = document.createElement('li');
  link5.innerHTML = '<a href="https://fatgarfield777.up.railway.app" target="_blank">%E2%9C%85 - fatgarfield777.up.railway.app</a>';
  var link6 = document.createElement('li');
  link6.innerHTML = '<a href="https://ubg.up.railway.app" target="_blank">%E2%9C%85 - ubg.up.railway.app</a>';
  linkList.appendChild(link1);
  linkList.appendChild(link2);
  linkList.appendChild(link3);
  linkList.appendChild(link4);
  linkList.appendChild(link5);
  linkList.appendChild(link6);
  var description = document.createElement('p');
  description.textContent = 'Use Ctrl+X to close';
  description.style.position = 'absolute';
  description.style.bottom = '10px';
  description.style.left = '50%';
  description.style.transform = 'translateX(-50%)';
  description.style.color = 'white';
  description.style.fontSize = '12px';
  box.appendChild(logo1);
  box.appendChild(logo2);
  box.appendChild(title);
  box.appendChild(keyList);
  box.appendChild(linkList);
  box.appendChild(description);
  document.body.appendChild(box);
  box.style.opacity = '1';
  document.addEventListener('keydown', function(e) {
    if (e.key === 'x' && e.ctrlKey) {
      box.style.display = 'none';
    }
  });
})();
